### ISSUE TITLE
Logo 

### ISSUE THREAD

**Issue by oscaringlez** [pagseguro/woocommerce#20]
Após instalação do modulo do pagseguro meu logo sumiu, alguem poderia me ajudar a solucionar esse problema?

Obrigado

**Comment by luansiqueira269** [comment]
Boa tarde amigo, consegue postar o link ou a url para análise?

**Comment by oscaringlez** [comment]
Ola eu posso postar, mas substitui por outro plugin.... mas caso precise posso reinstala-lo
http://contem.info/_site/

**Comment by felipebranco** [comment]
@oscaringlez o problema foi resolvido ? Acessei a url http://contem.info/_site/, a logo do site está normal! O módulo do PagSeguro está configurado também!

**Comment by oscaringlez** [comment]
Felipe nao posso lhe afirmar pois como nao obtive solução rapida optei por
instalar o plugin do claudio sanches , preciso instalar novamente pra lhe
responder, mesmo assim obrigado

Em 04/10/2017 4:08 PM, "Felipe Branco" <notifications@github.com> escreveu:

**Comment by felipebranco** [comment]
ok @oscaringlez foi disponibilizado no dia 14 de Julho uma nova versão do módulo do Pagseguro para Woocommerce quando instalar novamente verifique se resolveu o problema e qualquer dúvida entre em contato novamente.
