### ISSUE TITLE
Não funciona o Ligthbox e o transparante, só funciona no modo padrão

### ISSUE THREAD

**Issue by jhonnyrobson** [pagseguro/woocommerce#28]
No meu caso o plugin oficial do Pagseguro não funciona o Ligthbox e o transparante, só funciona no modo padrão, ou seja, de redirecionamento. Já o do Claudio Sanches funciona legal, só não consigo diminuir os campos do formulário, é muita coisa pra preencher. Quando removo os campos, dá erro, alguém pode me ajudar?

**Comment by felipebranco** [comment]
@jhonnyrobson Eu repliquei o erro relatado por você e será enviado para a equipe de desenvolvimento realizar a correção dos bugs.
