### ISSUE TITLE
Pagamento Recorrente 

### ISSUE THREAD

**Issue by brunokunace** [pagseguro/woocommerce#29]
Boa noite,  não vi informação sobre usar o pagamento recorrente nesse módulo. 
Existe essa opção? 
Precisava gerar uma forma de pagamento de taxa de condomínio para um cliente pelo pagseguro e não sei como utilizar.  Poderia me dar uma sugestão?

**Comment by felipebranco** [comment]
@brunokunace Não existe essa opção ainda de pagamento recorrente nesse módulo, mas está em desenvolvimento pela equipe do Pagseguro. Você pode utilizar o pagamento pelo Site do Pagseguro > Opção Minha Conta > Pagamento Recorrente e criar seu plano recorrente.
