### ISSUE TITLE
Retorno não está alterando o status do pedido

### ISSUE THREAD

**Issue by grimpa** [pagseguro/woocommerce#33]
Olá!

Estou testando no Sandbox. A notificação é enviada normalmente com status 200, até aí OK!

O problema é que no Wordpress não é atualizado o status do pedido automaticamente, após a notificação.

Estou utilizando:
- WP - 4.9.4–pt_BR 
- Woo - 3.3.3
- Woo PagSeguro Oficial - 2.0.0

Alguém poderia me ajudar?
Desde já agradeço.

**Comment by grimpa** [comment]
ok!

A Solução foi desinstalar a versão oficial do PagSeguro e Utilizar a versão do Claudio Sanches [https://br.wordpress.org/plugins/woocommerce-pagseguro/].

Resolveu meu problema!

**Comment by pocesar** [comment]
é bizarro, parece que eles nem testam o próprio código, também resolvi o meu problema assim, usando o do sanches
